# Site settings
title: Survival Trial - The Ultimate Test
email: info@survivaltrial.com
description: > # this means to ignore newlines until "baseurl:"
Survival Trial is a survival based adventure race that incorporates orienteering, first aid, disaster response, defensive shooting, and physical obstacles.
baseurl: "http://jonweiler.github.io/" # the subpath of your site, e.g. /blog/
url: "http://jonweiler.github.io/" # the base hostname & protocol for your site
twitter_username: survivaltrial
github_username:  jonweiler

# Build settings
markdown: kramdown
