# Site wide configuration

title:  Survival Trial 
description:  Survival Trial is a survival based adventure race that incorporates land navigation/orienteering, trekking, physical obstacles, mental challenges, distaster response, defensive shooting scenarios, and emergency medical situations.
logo: stlogo.gif
teaser: stteaser.gif
locale:  United States of America
url: http://survivaltrial.com



# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  
# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
  provider : disqus
  disqus :
    short_name : survivaltrial
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light  


# Site owner
owner:
  name:  Jon Weiler
  email:  info@survivaltrial.com
  twitter: survivaltrial
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:  survivaltrial

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-62813135-1'
  getclicky :
    site_id :


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
